import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Camera, Check, Copy, Database, Download, Edit3, ExternalLink, FileJson, Search, Upload, Wand2, AlertTriangle } from 'lucide-react';
import './styles.css';

type Confidence = { name: number; number: number; setCode: number; language: number };
type ScannerResult = {
  rawName: string | null; basePokemonName: string | null; suffix: string | null; translatedBaseName: string | null;
  cardmarketName: string | null; fullNumber: string | null; searchNumber: string | null; setCode: string | null; setName: string | null;
  languageGuess: string | null; languageCode: string | null; cardType: string | null; cardVersion: string | null; confidence: Confidence; warnings: string[];
};
type Card = ScannerResult & { id: string; originalName: string; languageLabel: string; condition: string; price: string; cardmarketUrl: string; createdAt: string; thumbnail?: string };
type Mappings = { pokemon: Record<string,string>; sets: Record<string,string> };

const POKEMON: Record<string,string> = { Durengard:'Aegislash', Glurak:'Charizard', Mewtu:'Mewtwo', Chillabell:'Cinccino', Schnuthelm:'Shelmet', Fukano:'Growlithe', Roserade:'Roserade', Barschuft:'Basculin', Shardrago:'Druddigon', Pikachu:'Pikachu', Oricorio:'Oricorio', 'Mega Glurak X':'Mega Charizard X', 'Mega Glurak Y':'Mega Charizard Y', 'Alola Vulpix':'Alolan Vulpix', 'Galar Lavados':'Galarian Moltres', 'Hisui Zoroark':'Hisuian Zoroark' };
const SETS: Record<string,string> = { SSH:'Sword-Shield', RCL:'Rebel-Clash', DAA:'Darkness-Ablaze', VIV:'Vivid-Voltage', BST:'Battle-Styles', CRE:'Chilling-Reign', EVS:'Evolving-Skies', FST:'Fusion-Strike', BRS:'Brilliant-Stars', ASR:'Astral-Radiance', LOR:'Lost-Origin', SIT:'Silver-Tempest', CRZ:'Crown-Zenith', CPA:'Champions-Path', SHF:'Shining-Fates', CEL:'Celebrations', PGO:'Pokemon-GO', SVI:'Scarlet-Violet', PAL:'Paldea-Evolved', OBF:'Obsidian-Flames', MEW:'Pokemon-151', PAR:'Paradox-Rift', PAF:'Paldean-Fates', TEF:'Temporal-Forces', TWM:'Twilight-Masquerade', SFA:'Shrouded-Fable', SCR:'Stellar-Crown', SSP:'Surging-Sparks', PRE:'Prismatic-Evolutions', JTG:'Journey-Together', DRI:'Destined-Rivals', BLK:'Black-Bolt', WHT:'White-Flare', SVP:'Scarlet-Violet-Promos', MEG:'Mega-Evolution', PFL:'Phantasmal-Flames', ASC:'Ascended-Heroes', POR:'Perfect-Order', CHR:'Chaos-Rising' };
const suffixes = ['VMAX','VSTAR','BREAK','LV.X','EX','ex','GX','V'];
const conditions = ['Near Mint','Excellent','Good','Light Played','Played','Poor'];
const cardTypes = [{label:'Normal', v:''},{label:'EX / V', v:'V1'}, {label:'Illustration Rare / Full Art', v:'V2'}, {label:'Special Illustration Rare', v:'V3'}, {label:'Gold / Secret Rare', v:'V4'}];

const load = <T,>(key:string, fallback:T):T => { try { return JSON.parse(localStorage.getItem(key) || '') as T; } catch { return fallback; } };
const save = (key:string, value:unknown) => localStorage.setItem(key, JSON.stringify(value));
const reverseSets = (sets:Record<string,string>) => Object.fromEntries(Object.entries(sets).map(([k,v]) => [norm(v), k]));
const norm = (s:string) => s.trim().toLowerCase().replace(/\s+/g,'-');
function detectSuffix(raw:string){ const hit = suffixes.find(s => new RegExp(`\\b${s.replace('.','\\.')}\\b`, 'i').test(raw)); return { suffix: hit || null, base: hit ? raw.replace(new RegExp(`\\b${hit.replace('.','\\.')}\\b`, 'i'),'').trim() : raw.trim() }; }
function translatePokemon(base:string, pokemon:Record<string,string>){ return pokemon[base] || pokemon[Object.keys(pokemon).find(k=>k.toLowerCase()===base.toLowerCase()) || ''] || base; }
function buildCardmarketName(raw:string, pokemon:Record<string,string>){ const {base, suffix} = detectSuffix(raw); const translated = translatePokemon(base, pokemon); return { basePokemonName: base, suffix, translatedBaseName: translated, cardmarketName: suffix ? `${translated}-${suffix.toUpperCase()}` : translated }; }
function normalizeCardNumber(input:string|null){ if(!input) return {fullNumber:null, searchNumber:null}; const s = input.toUpperCase().replace(/\s/g,''); const slash = s.match(/(\d{1,4})\/(\d{1,4})/); if(slash) return {fullNumber: slash[0], searchNumber: slash[1]}; const special = s.match(/(TG\d{1,3}|GG\d{1,3}|SV\d{1,3})/); if(special) return {fullNumber:special[1], searchNumber:special[1]}; const num = s.match(/\b\d{1,4}\b/); return {fullNumber:num?.[0] || null, searchNumber:num?.[0] || null}; }
function cleanPriceInput(v:string){ const m = v.replace(/\./g,',').match(/(\d+[,\.]?\d*)/); return m ? m[1].replace('.',',') : ''; }
function detectLanguage(text:string){ if(/[ぁ-んァ-ン一-龯]/.test(text)) return {label:'Japanisch', code:'7', c:.9}; if(/Schwäche|Resistenz|Rückzug|Entwickelt sich aus|Fähigkeit/i.test(text)) return {label:'Deutsch', code:'3', c:.85}; if(/Weakness|Resistance|Retreat|Evolves from|Ability/i.test(text)) return {label:'Englisch', code:'1', c:.85}; return {label:'Deutsch', code:'3', c:.45}; }
function buildUrl(r:ScannerResult){ const setName=r.setName||''; const name=r.cardmarketName||''; const code=r.setCode||''; const num=r.searchNumber||''; const lang=r.languageCode||'3'; const version = r.cardVersion ? `-${r.cardVersion}` : ''; return `https://www.cardmarket.com/de/Pokemon/Products/Singles/${setName}/${name}${version}-${code}${num}?sellerCountry=7&language=${lang}`; }
async function scanCardWithAI(text:string, mappings:Mappings):Promise<ScannerResult>{
  const warnings:string[]=[]; const raw = text || '';
  const numberMatch = raw.match(/\b\d{1,4}\s*\/\s*\d{1,4}\b|\b(?:TG|GG|SV)\d{1,3}\b/i);
  const {fullNumber, searchNumber}=normalizeCardNumber(numberMatch?.[0]||null);
  const setCode = Object.keys(mappings.sets).find(c => new RegExp(`\\b${c}\\b`, 'i').test(raw)) || null;
  const setNameByText = Object.values(mappings.sets).find(n => raw.toLowerCase().includes(n.toLowerCase().replaceAll('-',' ')) || raw.toLowerCase().includes(n.toLowerCase()));
  const setName = setCode ? mappings.sets[setCode] : (setNameByText || null);
  const code = setCode || (setName ? reverseSets(mappings.sets)[norm(setName)] : null);
  const known = [...Object.keys(mappings.pokemon), ...Object.values(mappings.pokemon)].sort((a,b)=>b.length-a.length);
  const nameHit = known.find(n => new RegExp(n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'), 'i').test(raw));
  let rawName = nameHit || null;
  const suffix = suffixes.find(s => new RegExp(`\\b${s.replace('.','\\.')}\\b`, 'i').test(raw));
  if(rawName && suffix && !new RegExp(`\\b${suffix.replace('.','\\.')}\\b`, 'i').test(rawName)) rawName = `${rawName} ${suffix}`;
  if(!rawName) warnings.push('Name nicht sicher erkannt – bitte manuell ergänzen.');
  if(!fullNumber) warnings.push('Kartennummer nicht sicher erkannt – bitte prüfen.');
  if(!code && !setName) warnings.push('Set nicht erkannt – Setcode oder Setname eingeben.');
  const nameParts = rawName ? buildCardmarketName(rawName, mappings.pokemon) : {basePokemonName:null,suffix:null,translatedBaseName:null,cardmarketName:null};
  const lang = detectLanguage(raw);
  const cardVersion = /special illustration|sar|sir/i.test(raw) ? 'V3' : /illustration|full art|trainer gallery|TG\d/i.test(raw) ? 'V2' : /gold|secret/i.test(raw) ? 'V4' : (suffix && /EX|ex|V$/i.test(suffix) ? 'V1' : '');
  return { rawName, ...nameParts, fullNumber, searchNumber, setCode:code, setName:setName || (code ? mappings.sets[code] : null), languageGuess:lang.label, languageCode:lang.code, cardType: cardTypes.find(t=>t.v===cardVersion)?.label || 'Normal', cardVersion, confidence:{name:rawName?.includes(' ') ? .82 : rawName ? .7 : .1, number:fullNumber?.includes('/') ? .95 : fullNumber ? .8 : .1, setCode:code ? .75 : .1, language:lang.c}, warnings };
}
function download(name:string, content:string, type='application/json'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); }
function csv(cards:Card[]){ const cols=['originalName','cardmarketName','fullNumber','searchNumber','setCode','setName','languageLabel','condition','cardType','cardVersion','price','cardmarketUrl','createdAt']; return [cols.join(';'),...cards.map(c=>cols.map(k=>`"${String((c as any)[k]||'').replaceAll('"','""')}"`).join(';'))].join('\n'); }

function App(){
  const [mappings,setMappings]=useState<Mappings>(()=>load('cwp-mappings',{pokemon:POKEMON,sets:SETS}));
  const [cards,setCards]=useState<Card[]>(()=>load('cwp-cards',[]));
  const [scan,setScan]=useState<ScannerResult|null>(null); const [thumb,setThumb]=useState<string>(); const [manual,setManual]=useState(''); const [tab,setTab]=useState<'scan'|'collection'|'db'>('scan'); const [filter,setFilter]=useState(''); const [busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null);
  const persistCards=(v:Card[])=>{setCards(v);save('cwp-cards',v)}; const persistMappings=(v:Mappings)=>{setMappings(v);save('cwp-mappings',v)};
  const runScan=async()=>{ setBusy(true); try{ const r=await scanCardWithAI(manual,mappings); setScan(r); }catch{ setScan({rawName:null,basePokemonName:null,suffix:null,translatedBaseName:null,cardmarketName:null,fullNumber:null,searchNumber:null,setCode:null,setName:null,languageGuess:'Deutsch',languageCode:'3',cardType:'Normal',cardVersion:'',confidence:{name:0,number:0,setCode:0,language:.4},warnings:['KI-Scanner konnte keine sicheren Daten ableiten. Workflow läuft manuell weiter.']}); } finally{setBusy(false)} };
  const updateScan=(k:keyof ScannerResult,v:any)=> setScan(s=>s?{...s,[k]:v}:s);
  const rebuildName=()=>{ if(!scan?.rawName)return; const n=buildCardmarketName(scan.rawName,mappings.pokemon); setScan({...scan,...n}); };
  const resolveSet=()=>{ if(!scan)return; const code = scan.setCode?.toUpperCase() || (scan.setName ? reverseSets(mappings.sets)[norm(scan.setName)] : null); const name = scan.setName || (code ? mappings.sets[code] : null); setScan({...scan,setCode:code,setName:name}); };
  const saveCard=()=>{ if(!scan)return; const card:Card={...scan,id:crypto.randomUUID(),originalName:scan.rawName||'',languageLabel:scan.languageGuess||'',condition:'Near Mint',price:'',cardmarketUrl:buildUrl(scan),createdAt:new Date().toISOString(),thumbnail:thumb}; persistCards([card,...cards]); setTab('collection'); };
  const visible=cards.filter(c=>JSON.stringify(c).toLowerCase().includes(filter.toLowerCase()));
  return <div className="app"><header><div><h1>Card Wizard Pro</h1><p>KI-Scanner für Pokémon-TCG Screenshots</p></div><Wand2/></header><nav><button onClick={()=>setTab('scan')} className={tab==='scan'?'on':''}>Scanner</button><button onClick={()=>setTab('collection')} className={tab==='collection'?'on':''}>Sammlung</button><button onClick={()=>setTab('db')} className={tab==='db'?'on':''}>Datenbanken</button></nav>
  {tab==='scan'&&<main><section className="hero"><Camera size={42}/><h2>Bild rein → strukturierte Kartendaten raus</h2><p>Der KI-Scanner macht Vorschläge. Alles bleibt editierbar; OCR/eBay-Fehler blockieren nie den Workflow.</p><input ref={input} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0]; if(f){const r=new FileReader(); r.onload=()=>setThumb(String(r.result)); r.readAsDataURL(f)}}}/><button className="primary" onClick={()=>input.current?.click()}><Upload/> Bild hochladen</button>{thumb&&<img className="thumb" src={thumb}/>}</section><section className="card"><label>Optionaler Text / erkannte Hinweise / manuelle Scan-Hilfe</label><textarea value={manual} onChange={e=>setManual(e.target.value)} placeholder="z. B. Durengard EX 151/086 WHT Schwäche Rückzug..."/><button className="primary" onClick={runScan} disabled={busy}>{busy?'KI-Scanner analysiert…':'KI-Scanner starten'}</button></section>{scan&&<section className="card"><h2>Review & Bearbeiten</h2>{scan.warnings.map(w=><p className="warn" key={w}><AlertTriangle size={16}/> {w}</p>)}{(['rawName','cardmarketName','fullNumber','searchNumber','setCode','setName','languageGuess','languageCode'] as (keyof ScannerResult)[]).map(k=><div className="field" key={k}><span>{k}</span><input value={String(scan[k]||'')} onChange={e=>updateScan(k,e.target.value)}/><button><Check/> Passt</button></div>)}<div className="row"><button onClick={rebuildName}><Edit3/> Namen neu übersetzen</button><button onClick={resolveSet}><Database/> Set auflösen</button></div><div className="field"><span>Kartentyp</span><select value={scan.cardVersion||''} onChange={e=>{const t=cardTypes.find(x=>x.v===e.target.value); setScan({...scan, cardVersion:e.target.value, cardType:t?.label||'Normal'})}}>{cardTypes.map(t=><option key={t.v} value={t.v}>{t.label} {t.v&&`(${t.v})`}</option>)}</select></div><h3>Cardmarket-Link</h3><code>{buildUrl(scan)}</code><div className="row"><button onClick={()=>navigator.clipboard.writeText(buildUrl(scan))}><Copy/> Kopieren</button><button onClick={()=>window.open(buildUrl(scan),'_blank')}><ExternalLink/> Öffnen</button></div><button className="primary" onClick={saveCard}>Karte speichern</button></section>}</main>}
  {tab==='collection'&&<main><section className="card"><div className="search"><Search/><input placeholder="Suche, Set, Sprache, Zustand…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="row"><button onClick={()=>download('card-wizard-collection.json',JSON.stringify(cards,null,2))}><FileJson/> JSON Export</button><button onClick={()=>download('card-wizard-collection.csv',csv(cards),'text/csv')}><Download/> CSV Export</button><label className="button">JSON Import<input hidden type="file" accept="application/json" onChange={async e=>{const f=e.target.files?.[0]; if(f) persistCards(JSON.parse(await f.text()))}}/></label></div></section>{visible.map(c=><section className="card saved" key={c.id}>{c.thumbnail&&<img src={c.thumbnail}/>}<div><h2>{c.cardmarketName||c.originalName}</h2><p>{c.setName} · {c.fullNumber} · {c.languageLabel} {c.price?`· ${c.price} €`:<b className="badge">Preis fehlt</b>}</p><div className="field"><span>Preis</span><input value={c.price} onChange={e=>persistCards(cards.map(x=>x.id===c.id?{...x,price:cleanPriceInput(e.target.value)}:x))} placeholder="ab 0,89 €"/></div><div className="row"><button onClick={()=>window.open(c.cardmarketUrl,'_blank')}>Cardmarket</button><button onClick={()=>persistCards(cards.filter(x=>x.id!==c.id))}>Löschen</button></div></div></section>)}</main>}
  {tab==='db'&&<main><Db title="Pokémon Deutsch → Englisch" data={mappings.pokemon} onChange={pokemon=>persistMappings({...mappings,pokemon})}/><Db title="SetCode → SetName" data={mappings.sets} onChange={sets=>persistMappings({...mappings,sets})}/><section className="card"><button onClick={()=>persistMappings({pokemon:POKEMON,sets:SETS})}>Startdaten zurücksetzen</button><button onClick={()=>download('card-wizard-mappings.json',JSON.stringify(mappings,null,2))}>Mappings exportieren</button></section></main>}
  </div>;
}
function Db({title,data,onChange}:{title:string;data:Record<string,string>;onChange:(d:Record<string,string>)=>void}){ const [k,setK]=useState(''),[v,setV]=useState(''); return <section className="card"><h2>{title}</h2><div className="field"><input placeholder="Key" value={k} onChange={e=>setK(e.target.value)}/><input placeholder="Wert" value={v} onChange={e=>setV(e.target.value)}/><button onClick={()=>{if(k&&v){onChange({...data,[k]:v});setK('');setV('')}}}>Hinzufügen</button></div><div className="maplist">{Object.entries(data).map(([a,b])=><p key={a}><b>{a}</b> → {b}<button onClick={()=>{const n={...data};delete n[a];onChange(n)}}>×</button></p>)}</div></section> }

createRoot(document.getElementById('root')!).render(<App/>);
